linbox/Makefile.am

Currently when ocl is enabled the ocl libraries are not used when linking liblinbox.so. This PR fix this situation.

ADD OCL_LIBS in the right place for correct linking when ocl is enabled

---

linbox.pc.in

Currently in `linbox.pc.in`, `libdir` is set to `@prefix@/lib` which ignore the scenario where `libdir` has been configured to something else on the command line (more commonly `/usr/lib64` for example). This PR correct that problem. I notice that `linbox-config.in` already has the correct value. It also goes further to take care of exotic scenario for `includedir` which I didn't do here.

Use the correct libdir in linbox.pc

---

configure.ac
interfaces/driver/Makefile.am
interfaces/maple/Makefile.am
interfaces/sage/Makefile.am

This adds the necessary bits to compile shared libraries on Windows.  For reference, see https://www.gnu.org/software/libtool/manual/html_node/LT_005fINIT.html (under win32-dll).
See https://trac.sagemath.org/ticket/22318 for the original issue.

Fixes linking interface modules as shared libraries on Windows

---

linbox/solutions/det.h
linbox/solutions/rank.inl

`B0` unfortunately conflicts with a standard macro in `termios.h`.  This is the same issue as in linbox-team/fflas-ffpack#57

Do not use 'B0' as a variable name

---

linbox/field/gf2.h

This is intended as a fix for issue #46 which identified problems in `linbox/fields/gf2.h` when using clang. My own opinion is that scrubbing is needed. Some parts where implementation specific. In the top part of we have a conditional definition which was failing with a full clang because the condition was not precise enough. When examined fully, the two alternatives give the same results - the gcc specialisation is just the internal implementation of the standard non-gcc alternative on the other branch.
At the bottom of the the file we have again a specialisation depending on standard and compiler. It should all work in all cases if a standard header is used rather than implementation dependent ones. In this case the last default branch was there probably because a specialised header …

Simplification in gf2.h headers. Be more standard conformant

---

linbox/matrix/matrixdomain/blas-matrix-domain.inl
tests/test-minpoly.C

test-minpoly has a very bad coverage: 
- integer minpoly was not tested
- only the zero, identity and canonical nilpotent matrix were tested.
This re-enables the test with random matrices and the test of integer matrices (fixing the bugs that lead them to be disabled) and updates the overall infrastructure of the test to a more modular form.

Improve test minpoly

---

macros/config-header.m4

Patch by Gonzalo Tornaria to remove all bashism in the configure scripts, making configure fail with dash-0.5.9.
See also https://trac.sagemath.org/ticket/23451

Remove bash-ism in configure scripts

---

linbox/algorithms/cra-domain.h
linbox/algorithms/cra-early-multip.h
linbox/algorithms/cra-full-multip-fixed.h
linbox/algorithms/cra-full-multip.h
linbox/algorithms/cra-givrnsfixed.h
linbox/algorithms/cra-single.h
linbox/algorithms/lazy-product.h
linbox/algorithms/rational-cra-full-multip.h
linbox/algorithms/signature.h
linbox/algorithms/varprec-cra-early-multip.h
linbox/algorithms/varprec-cra-early-single.h
tests/test-cra.C
tests/test-cradomain.C

The FullMultipCRA class in algorithms/cra-full-multip.h has been redesigned, as documented in that file. This has the benefit of good asymptotic performance in CRA even when the modulus sizes are different, such as when a CRA is restarted etc.
Rather than having four vectors for the shelves data, there is a single vector of structs and a convenient interface to iterate over the shelves (in reverse order). Many other classes that were diving into the internal details of FullMultipCRA can use this interface instead for simplicity. A few other classes are almost entirely eliminated as minor specializations of FullMultipCRA instead of rewriting the logic.

Cra full rewrite

---

.gitignore
linbox/util/serialization.h
linbox/util/serialization.inl
tests/test-serialization.C

The PR implements platform-independent serialization with associated tests.
The functions `uint64_t serialize(std::vector<uint8_t>& bytes, const T& value);` converts the value to bytes and add those to the specified vector, they return the number of bytes written. The counter part `unserialize` is implemented too.
Tricky cases implemented:
- Enforcing little-endian serialization, so there is a little bit more work to do on big-endian machines;
- `Integer` are nicely serialized (using the underlying mpz_struct);
- `BlasMatrix`, `SparseMatrix` and `BlasVector` can be serialized, as long as the underlying `Field::Element` is serializable.
Upcoming use cases:
- MPI communication requires endianness-resistant routines to transfer LinBox matrices or vectors. This PR also allows us to send only …

Routines for serialization

---

linbox/util/commentator.h
linbox/util/commentator.inl

`valgrind` was complaining because `cnull` initialization called open on `0`. Fixed by initializing `cnull` with `/dev/null`. 
Also fixes the indentation in a different commit, replacing tabs by spaces according to the descriptions at the end of the files.

Fix `cnull` init and commentator.* indentation.

---

linbox/integer.h

This PR cleans some check functions, namely `isOdd/Even` and `isPositive/Negative`.
It reduces the number of override functions for checking positivity, renames all in `isX` (instead of `isX` or `IsX`) and removes dependency on  Givaro check functions.
See Issue #137 for original comments.

Clean some check functions

---

linbox.pc.in

In the file `linbox.pc.in`, the placeholder `@LINBOXSAGE_LIBS@` was never substituted preventing the use of `pkg-config --libs linbox` for compiling code using LinBox.
As `git grep LINBOXSAGE` returns nothing, I assume it is a remaining artifact from some old and removed code and can be safely removed.

Remove @LINBOXSAGE_LIBS@ from linbox.pc.in

---

linbox/blackbox/toeplitz.inl
tests/Makefile.am
tests/test-toeplitz.C

I wrote an implementation of the Frobenius form algorithm presented [here](https://link.springer.com/chapter/10.1007%2F978-3-642-57201-2_30) (see algorithms/frobenius-large.h) and uncovered a bug in the Toeplitz black box implementation that causes apply/applyTranpose to compute incorrect results for asymmetric matrices.
I had previously fixed apply, but this is a pull request with tests for apply/applyTranspose and a fix for applyTranspose.

Add tests for toeplitz apply/applyTranspose with non-square dimensions

---

benchmarks/benchmark-order-basis.C
examples/bench-fft.C
examples/bench-matpoly-mult.C
examples/bench-new-fft.C
linbox/algorithms/matpoly-mult.h
linbox/algorithms/polynomial-matrix/matpoly-mult-fft-wordsize-three-primes.inl
linbox/algorithms/polynomial-matrix/matpoly-mult-fft.h
linbox/randiter/random-fftprime.h
tests/test-matpoly-mult.C
tests/test-order-basis.C

This PR fixes issue #175 
I change a little the interface to RandomFFTPrime and updated the code in linbox where it was necessary.
In doing so, I found a call to RandomFFTPrime that seems weird. In `linbox/algorithms/matpoly-mult.h`, there is four calls to generates random FFT primes less than `bit` and not `2^bit` as I would have expected. `bit` is indeed a number of bits, so a small number. Do we really want prime less than `bit` or is it a typo ?

Fixing #175: RandomFFTPrime

---

tests/test-solve.C

order of catch can matter with polymorphic execeptions.

catch by ref. / order of catch

---

linbox/algorithms/lifting-container.h
linbox/randiter/abstract.h
linbox/randiter/archetype.h
linbox/randiter/envelope.h
linbox/randiter/generic.h
linbox/randiter/lidia-gfq.h
linbox/randiter/modular-balanced.h
linbox/randiter/multimod-randomprime.h
linbox/randiter/param-fuzzy.h
linbox/ring/ntl/ntl-gf2e.h
linbox/ring/ntl/ntl-lzz_p.h
linbox/ring/ntl/ntl-lzz_pe.h
linbox/ring/ntl/ntl-lzz_pex.h
linbox/ring/ntl/ntl-lzz_px.h
linbox/ring/ntl/ntl-rr.h
linbox/ring/ntl/ntl-zz_p.h
linbox/ring/ntl/ntl-zz_pe.h
linbox/solutions/hadamard-bound.h
linbox/util/serialization.inl
linbox/vector/stream.h
tests/test-randiter-nonzero-prime.C
tests/test-serialization.C

The types used for seeds in LinBox vary a lot and cause numerous type conversion ambiguities with Givaro random iterators on OS-X where size_t is not silently converted into an uint64_t: https://ci.inria.fr/linbox/job/LinBox/290/
This PR fixes all such issues by changing all seeds to be uint64_t (excpect the one of Mersenne Twister which is already uint32_t since everything there is on 32 bits).

Seed is uint64 t

---

linbox/algorithms/cra-builder-full-multip.h
linbox/solutions/charpoly.h
linbox/solutions/hadamard-bound.h
linbox/solutions/minpoly.h

Currently the charpoly and minpoly over ZZ use early terminated Chinese Remainder, with a fixed number of stabilization checks. This is a heuristic algorithm and has caused user test-cases to fail ( see
https://trac.sagemath.org/ticket/21579 and https://trac.sagemath.org/ticket/15535)
In the previous release, we made the decision to leave the heuristic variant as a default, claiming we would adress the problem. 
We therefore patched LinBox in sage, and other packagers had to also patch the library. See https://trac.sagemath.org/ticket/24214#comment:17
and following comments
We still did not address the problem, and I suggest the following changes implemented in this PR: 
- switch between Heuristic (EarlyTermination CRA) or Deterministic (FullCRA) in the charpoly and minpoly with …

Full CRA charpoly and minpoly

---

configure.ac
macros/debug.m4

Uniformize fabi-version=6 only if gcc version < 5 in givaro/fflas/linbox.
Required as a kludge before cleanup the full autotools mechanisms, as otherwise there are incompatibilities between givaro/fflas/linbox.
See similar PR in givaro/linbox: [givaro-PR151](https://github.com/linbox-team/givaro/pull/151) and [fflas PR305](https://github.com/linbox-team/fflas-ffpack/pull/305).

fabi-version=6 only if gcc version < 5

---

linbox.pc.in

they remain if the script is run under ksh, leading to broken .pc file

remove redundant 1st and last lines

---

linbox/algorithms/polynomial-matrix/fft-integral.inl

Fixing issue #262 
Adding `#ifdef __FFLASFFPACK_HAVE_SSE4_1_INSTRUCTIONS` to protect use of Simd128 in FFT code.

Fix undefined Simd128 in FFT code when compiled without SSE 4.1

---

configure.ac
macros/common.m4
macros/debug.m4

This PR removes support for gcc4 (same as linbox-team/givaro#170) and use -mcpu when -march flag is not supported ((same as linbox-team/givaro#168)

Update autotools scripts

---

linbox/vector/bit-vector.inl

It was previously long (64-bit integers), but this will not be the
case on 32-bit systems.
Closes: #273

Use std::ptrdiff_t for vector iterator difference type

---

linbox/ring/ntl/ntl-gf2e.h
linbox/ring/ntl/ntl-lzz_p.h
linbox/ring/ntl/ntl-lzz_pe.h
linbox/ring/ntl/ntl-lzz_px.h
linbox/ring/ntl/ntl-rr.h
linbox/ring/ntl/ntl-zz.h
linbox/ring/ntl/ntl-zz_p.h
linbox/ring/ntl/ntl-zz_pe.h

Fix the conflict implied by the joint merge of PR #257  and the givaro PR#184
Also added a `Caster` for `NTL::ZZ` and used it to fix abusive casts of `integer` to `int32_t`

fix for Residu_t as new type in randiters; add a Caster for NTL::ZZ

---

linbox/matrix/matrixdomain/opencl-domain-util.inl
linbox/matrix/matrixdomain/opencl-domain.h
linbox/matrix/matrixdomain/opencl-domain.inl
macros/mpi-check.m4
macros/ocl-check.m4

OpenCL code in LinBox does not compile, and therefore, when enabled, the whole library stops compiling. See #275.
This PR
* fixes many of the compilation issues, but leaves one unsolved for future work
* stop enabling OpenCL automatically when --with-ocl is not specified by opencl found

Fix OpenCL issues

---

linbox/algorithms/bbcharpoly.h
linbox/algorithms/blackbox-container-base.h
linbox/algorithms/blackbox-container.h
linbox/algorithms/massey-domain.h
linbox/algorithms/wiedemann.h
tests/test-regression.C

The current minpoly does not ensure that the sequence is not the zero sequence, i.e. the projection vectors are not orthogonal.
This clearly expose a bug for charpoly with the zero matrix.
This PR fixes this issue by checking the dot product of the projection vectors is not zero.
A test has been added for charpoly to cover symmetric and non symmetric case.

problem with zero sequence for minpoly/charpoly

---

linbox/matrix/matrixdomain/opencl-domain.h

Fixes this error when building with OpenCL support:
```
../linbox/matrix/matrixdomain/opencl-domain.h: In instantiation of ‘const LinBox::SubmatrixAdapter<_Matrix>::Element& LinBox::SubmatrixAdapter<_Matrix>::setEntry(size_t, size_t, const Element&) [with _Matrix = LinBox::BlasMatrix<Givaro::Modular<double>, std::vector<double> >; Element = double; size_t = long unsigned int]’:
../linbox/matrix/matrixdomain/opencl-domain-memory.inl:209:21:   required from ‘Operand1& LinBox::OpenCLMatrixDomain<Field_>::oclDepadMatrix(cl_mem, int, int, int, Operand1&) const [with T = double; Operand1 = LinBox::SubmatrixAdapter<LinBox::BlasMatrix<Givaro::Modular<double>, std::vector<double> > >; Field_ = Givaro::Modular<double>; cl_mem = _cl_mem*]’
../linbox/matrix/matrixdomain/opencl-domain-memory.inl:315:37 …
```

Set SubmatrixAdapter::setEntry return type to void

---

linbox/matrix/sparsematrix/sparse-ell-matrix.h
linbox/matrix/sparsematrix/sparse-ellr-matrix.h

The const cast was added for gcc-14 compatibilty, but this breaks macos clang. The private field is _ld, not ld without underscore. Its somewhat surprising that it doesn't fail on gcc-14, presumably because the code path is unused.

Fix const cast for _ld (note the underscore)

---

linbox/blackbox/apply.h

Fixes #304 by adding one byte to the allocated size, based on the rationale offered by Jerry James, @jamesjer, in https://github.com/linbox-team/linbox/issues/304.
In addition, a new local variable is introduced for the size in question to reduce repetition.
-----
I tested this with `-D_FORTIFY_SOURCE=3` and confirmed that the tests pass.

Fix the size formula for an allocation

---

linbox/blackbox/diagonal.h
linbox/blackbox/fibb.h
linbox/blackbox/permutation.h
linbox/matrix/densematrix/blas-matrix.inl
linbox/matrix/sparsematrix/read-write-sparse.inl
linbox/matrix/sparsematrix/sparse-sequence-vector.h

Both iterator and indexed iterators now have constructor with only beg/end (on rows)
then subiterator (on columns) is set only if beg != end (that is if matrix is non-empty).
In the whole LinBox library, the above constructor suffices.
When beg != end it initializes to beg->begin(); but the latter was ill-defined otherwise, causing some instability.
If needed, it is simple enough to reintroduce the 3 arguments constructor, 
for when it is known in advance that beg != end, and when the third argument is different from "beg->begin()" ...

Sparse Sequence Iterators constructors with only beg/end arguments
