linbox-team/linbox

examples/bench-fft.C, examples/bench-new-fft.C, linbox/algorithms/polynomial-matrix/polynomial-fft-algorithms.h, linbox/algorithms/polynomial-matrix/polynomial-fft-butterflies.h, linbox/algorithms/polynomial-matrix/polynomial-fft-init.h, linbox/algorithms/polynomial-matrix/polynomial-fft-transform-simd.inl, linbox/algorithms/polynomial-matrix/polynomial-fft-transform.h, linbox/algorithms/polynomial-matrix/simd-additional-functions.h, linbox/algorithms/polynomial-matrix/simd.h, linbox/linbox-config.h, linbox/randiter/random-fftprime.h
=> Revert "Most all my new FFT stuff in a decent state"

linbox/matrix/matrixdomain/blas-matrix-domain.inl, linbox/solutions/minpoly.h, tests/test-regression.C
Fixing the neverending minpoly with 0x0 matrix bug.
The 0x0 charpoly bug has been fixed in fflas-ffpack https://github.com/linbox-team/fflas-ffpack/pull/144
=> Zero dim charpoly

linbox/algorithms/smith-form-sparseelim-local.h, linbox/algorithms/smith-form-sparseelim-poweroftwo.h
=> forgot last permutation

linbox/algorithms/polynomial-matrix/polynomial-fft-init.h
Small change to help Bruno with refactorization_modular in givaro
=> Remove unnecessary call to precomp_p (only (mul_)precomp_b is called)

linbox/ring/polynomial-ring.h
=> replace enable_if machinery by some good ol' template traits

examples/solve.C
Also uniformized usage of std namespace.
Some `Timer chrono;` was wrongly commented out.
=> Made solve example compile again

linbox/randiter/random-prime.h
=> add an accessor to the bitsize of a randomprime generator

linbox/algorithms/bbcharpoly.h, linbox/algorithms/blackbox-block-container-base.h, linbox/algorithms/polynomial-matrix/polynomial-fft-transform.h, linbox/algorithms/smith-form-valence.h, tests/test-rank.h
=> No simd64 on i386

linbox.pc.in, linbox/polynomial/dense-polynomial.h
Fix #171 
Edit:
I mixed my different branches for the two PR,  commit 426eb97 should not be taken into account, it is for another PR.
=> Fix dense poly header requirements

benchmarks/benchmark-solveCRA.C, benchmarks/gen-blocks.C, examples/blassolve.C, examples/checksolve.C, examples/minpoly.C, examples/solve.C, examples/solverat.C, linbox/algorithms/bbsolve.h, linbox/algorithms/cia.h, linbox/algorithms/hybrid-det.h, linbox/solutions/charpoly.h, linbox/solutions/det.h, linbox/solutions/is-positive-definite.h, linbox/solutions/is-positive-semidefinite.h, linbox/solutions/methods.h, linbox/solutions/minpoly.h, linbox/solutions/rank.h, linbox/solutions/rank.inl, linbox/solutions/solve.h, tests/test-det.C, tests/test-random-matrix.C, tests/test-rank.h, tests/test-regression.C
**Work in progress: Still have to renamed BlasElimination to DenseElimination**
In favour of Method::SparseElimination at the only place it was really used.
=> Removed Method::NonBlasElimination and renamed BlasElimination to DenseElimination

examples/sparseelimdet.C, examples/sparseelimrank.C, examples/sparsesolverat.C, linbox/algorithms/gauss-gf2.h, linbox/algorithms/gauss.h, linbox/algorithms/gauss/gauss-det-gf2.inl, linbox/algorithms/gauss/gauss-det.inl, linbox/algorithms/gauss/gauss-rank-gf2.inl, linbox/algorithms/gauss/gauss-rank.inl, linbox/algorithms/gauss/gauss-solve-gf2.inl, linbox/algorithms/gauss/gauss-solve.inl, linbox/algorithms/hybrid-det.h, linbox/algorithms/smith-form-valence.h, linbox/matrix/matrixdomain/blas-matrix-domain.h, linbox/matrix/matrixdomain/opencl-domain.h, linbox/solutions/Makefile.am, linbox/solutions/det.h, linbox/solutions/rank.h, linbox/solutions/rank.inl, linbox/solutions/solve.h, tests/test-blas-domain.C, tests/test-matrix-domain.h, tests/test-qlup.C, tests/test-rank.h
As suggested during solve refacto review, these have been renamed:
- solvein
- rankin
- detin
=> Renamed solvein to solveInPlace and similar

linbox/algorithms/wiedemann.h, linbox/algorithms/wiedemann.inl, tests/test-solve.C
Turns out `testSingularInconsistentSolve(F, stream3, stream2, "Wiedemann", Method::Wiedemann ())` fails
=> Uncommented test-solve.C

tests/test-regression.C
=> testing issue #189

linbox/algorithms/block-massey-domain.h, linbox/algorithms/echelon-form.h, linbox/algorithms/rational-solver.inl, linbox/matrix/factorized-matrix.h, linbox/matrix/factorized-matrix.inl, linbox/matrix/matrixdomain/blas-matrix-domain.inl, linbox/solutions/solve/solve-dense-elimination.h, tests/test-regression.C, tests/test-solve-full.C
according to the change in fflas-ffpack
=> LQUPto PLUQ

linbox/util/serialization.inl
Fixes #204 
-> Should check Jenkins status with that fix.
=> Fixed serialization for GMP 32 bits

linbox/matrix/densematrix/blas-matrix.h, linbox/matrix/densematrix/blas-matrix.inl, linbox/matrix/densematrix/blas-submatrix.inl, linbox/vector/blas-vector.h
=> Cleaned wrong getPointer from matrix

doc/mainpage.doxy, tests/test-blas-domain.C, tests/test-block-wiedemann.C, tests/test-hadamard-bound.C, tests/test-hom.C, tests/test-la-block-lanczos.C, tests/test-local-smith-form-sparseelim.C, tests/test-matpoly-mult.C, tests/test-mg-block-lanczos.C, tests/test-minpoly.C, tests/test-mpi-comm.C, tests/test-order-basis.C, tests/test-qlup.C, tests/test-solve-full.C, tests/test-sparse.C, tests/test-vector-domain.C
1/ seed before size
2/ size is sampling size (same type as cardinality) and should be used
=> refacto randiter (seed first)

examples/rr.C, linbox/algorithms/charpoly-rational.h, linbox/algorithms/classic-rational-reconstruction.h, linbox/algorithms/det-rational.h, linbox/algorithms/fast-rational-reconstruction.h, linbox/algorithms/minpoly-rational.h, linbox/algorithms/rational-cra-builder-early-single.h, linbox/algorithms/rational-cra-builder-full-multip.h, linbox/algorithms/rational-cra-var-prec.h, linbox/algorithms/rational-reconstruction-base.h, linbox/algorithms/rational-reconstruction.h, linbox/field/field-traits.h, linbox/field/hom.h, linbox/ring/ntl/ntl-zz.h
=> IntegerDom and ZRing<Integer> are not different anymore

examples/mats.C, linbox/algorithms/smith-form-adaptive.inl, linbox/algorithms/smith-form-local.h, linbox/ring/local-pir-modular.h, linbox/solutions/smith-form.h, tests/Makefile.am, tests/checker.C, tests/test-smith-form-binary.C, tests/test-smith-form-iliopoulos.C, tests/test-smith-form-valence.C
=> No NTL required for Smith form

examples/smithsparse.C, examples/sparseelimdet.C, examples/sparsesolverat.C, linbox/algorithms/gauss/gauss-gf2.inl, linbox/algorithms/gauss/gauss-nullspace.inl, linbox/algorithms/gauss/gauss.inl, linbox/matrix/plain-matrix.h, linbox/matrix/sparsematrix/sparse-sequence-vector.h, linbox/ring/ntl/ntl-gf2e.h, linbox/ring/ntl/ntl-lzz_p.h, linbox/ring/ntl/ntl-lzz_pe.h, linbox/ring/ntl/ntl-lzz_pex.h, linbox/ring/ntl/ntl-lzz_px.h, linbox/ring/ntl/ntl-rr.h, linbox/ring/ntl/ntl-zz_p.h, linbox/ring/ntl/ntl-zz_pe.h, linbox/solutions/det.h, linbox/util/commentator.inl, linbox/vector/blas-vector.h, linbox/vector/light_container.h, tests/test-cradomain.C
=> Comm gauss

README.md
- minor fixes
- more examples of usage of the auto-installer
- mention some dependencies for the auto-installer
=> Auto install : improving the README 

examples/Makefile.am, examples/athadet.C, examples/bench-matpoly-mult.C, examples/checksolve.C, examples/det.C, examples/doubledet.C, examples/echelon.C, examples/givaro-poly-local.C, examples/graph-charpoly.C, examples/iliopoulos2.C, examples/nullspacebasis.C, examples/nullspacebasis_rank.C, examples/nullspacebasis_rat.C, examples/poly-smith.C
=> Mathieu dut sik correct examples

examples/athadet.C, examples/bench-matpoly-mult.C, examples/checksolve.C, examples/det.C, examples/doubledet.C, examples/echelon.C, examples/givaro-poly-local.C, examples/graph-charpoly.C, examples/iliopoulos2.C, examples/nullspacebasis.C, examples/nullspacebasis_rank.C, examples/nullspacebasis_rat.C, examples/poly-smith.C
Several points are addressed:
* Some examples in the **linbox/examples** directory had wrong count of argc
* An example for nullspace over the rational is added.
* Some cosmetic corrections.
=> Correct examples and add one example for rational nullspace

linbox/blackbox/apply.h, linbox/util/serialization.inl
=> Replace dangerous pointer casts by memcopy

linbox/algorithms/blackbox-block-container-base.h, linbox/algorithms/blackbox-block-container.h, linbox/algorithms/matpoly-mult.h, linbox/algorithms/signature.h, linbox/blackbox/permutation.h, linbox/blackbox/triangular-fibb.h, linbox/blackbox/zero-one.inl, linbox/randiter/lidia-gfq.h, linbox/randiter/ntl-zz.h, linbox/ring/ntl/ntl-gf2e.h, linbox/ring/ntl/ntl-lzz_p.h, linbox/ring/ntl/ntl-lzz_pe.h, linbox/ring/ntl/ntl-lzz_pex.h, linbox/ring/ntl/ntl-lzz_px.h, linbox/ring/ntl/ntl-rr.h, linbox/ring/ntl/ntl-zz_p.h, linbox/ring/ntl/ntl-zz_pe.h
=> Ntl time cast
